---
# Development Inventory (51.20.78.235)
all:
  vars:
    ansible_connection: local
    app_name: happy-tails
    app_env: development
    
  children:
    local:
      hosts:
        51.20.78.235:
          ansible_host: 127.0.0.1
