---
# Development Inventory (13.53.137.119)
all:
  vars:
    ansible_connection: local
    app_name: happy-tails
    app_env: development
    
  children:
    local:
      hosts:
        13.53.137.119:
          ansible_host: 127.0.0.1
