---
# Staging Inventory
all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/happy-tails-key.pem
    app_name: happy-tails
    app_env: staging
    
  children:
    kubernetes:
      vars:
        kubernetes_version: "1.27"
        container_runtime: docker
      children:
        control_plane:
          hosts:
            k8s-staging-control-1:
              ansible_host: 10.1.1.10
        workers:
          hosts:
            k8s-staging-worker-1:
              ansible_host: 10.1.2.10
    
    docker_hosts:
      hosts:
        docker-staging-1:
          ansible_host: 10.1.3.10
